### ISSUE TITLE
SSL Certificate expired: codetime-api.datreks.com

### ISSUE THREAD

**Issue by KleinDevDE** [datreks/codetime-jetbrains#11]
The SSL certificate for **codetime-api.datreks.com** is expired.  
https://www.ssllabs.com/ssltest/analyze.html?d=codetime%2dapi.datreks.com&latest  
  
![image](https://github.com/datreks/codetime-jetbrains/assets/13904220/fc548ae2-1203-4394-812c-dd22bdb3685e)
![image](https://github.com/datreks/codetime-jetbrains/assets/13904220/76bcaeee-16d8-46ef-94a8-e0143b863e27)

**Comment by si9ma** [comment]
@KleinDevDE fixed!

**Comment by KleinDevDE** [comment]
Hi!
Hope you had a nice time since my last issue here.  
  
Sry to reopen this, but I think it's easier to have the same issue for the same problem, then repeatly open a new one.  
The certificate is expired again.  
![image](https://github.com/user-attachments/assets/238b9dc1-f2b3-452a-a5e5-a9cc8c0d15fd)
