### ISSUE TITLE
EAP 2021.1 Incompatible 

### ISSUE THREAD

**Issue by Foysal50x** [datreks/codetime-jetbrains#2]
Today I download WebStrom EAP version and I show an error Incompatible: require IDE Build 203.* or older.

 This plugin not capable with EAP version of Jetbrains products

**Comment by si9ma** [comment]
Can you provide me with your ide version detail. Click on Help section and in the drop-down click on About.

**Comment by Foysal50x** [comment]
WebStorm Version 2021.1 EAP
PhpStorm Version 2021.1 EAP
<img width="644" alt="Screenshot 2021-02-08 at 10 26 47 AM" src="https://user-images.githubusercontent.com/24409515/107175891-2811e780-69f8-11eb-92de-6db6e27c724e.png">


<img width="639" alt="Screenshot 2021-02-08 at 10 22 01 AM" src="https://user-images.githubusercontent.com/24409515/107175622-7f638800-69f7-11eb-886f-f88a63169cdc.png">

**Comment by si9ma** [comment]
@Faisal50x OK, I will fix it soon

**Comment by si9ma** [comment]
@Faisal50x Fixed! You can try again!
